:hivemq-link: http://www.hivemq.com
:hivemq-extension-docs-link: http://www.hivemq.com/docs/extensions/latest/
:hivemq-extension-docs-archetype-link: http://www.hivemq.com/docs/extensions/latest/#maven-archetype-chapter
:hivemq-blog-tools: http://www.hivemq.com/mqtt-toolbox
:maven-documentation-profile-link: http://maven.apache.org/guides/introduction/introduction-to-profiles.html
:hivemq-support: http://www.hivemq.com/support/

== HiveMQ Mqtt Message Log Extension

*Type*: Logging Extension

*Version*: 1.0.0

*License*: Apache License Version 2.0

=== Purpose

The HiveMQ MQTT Message Log Extension is a very useful HiveMQ Extension for debugging and development purposes. It provides the possibility to follow up on any clients communicating with the broker on the terminal.

*The extension logs the following events:*

* A client connects to HiveMQ
* A client sends a publish message
* A client sends a subscribe message
* A client disconnects from HiveMQ
* HiveMQ sends a publish message to a client


=== Installation

. Clone this repository into a Java 11 maven project.
. Run `mvn package` goal from Maven to build the extension.
. Move the file: "target/hivemq-mqtt-message-log-extension-1.0.0-distribution.zip" to the directory: "HIVEMQ_HOME/extensions"
. Unzip the file.
. Start HiveMQ.

=== Configuration

It is possible to opt out of specific log event types by adding a
*mqttMessageLog.properties* files to your +<HIVEMQ_HOME>/hivemq-mqtt-message-log-extension+  folder.
There is an example file available which removes the logging of publish messages. Just rename it to *mqttMessageLog.properties*

This properties file could have the following entries:

* client-connect=false|true
* client-disconnect=false|true
* publish-received=false|true
* publish-send=false|true
* subscribe-received=false|true

Missing entries default to true.

=== First Steps

Connect with an {hivemq-blog-tools}[MQTT client] of your choice. You should see a log message with its identifier, MQTT version, and all other connect options.

== Contributing

If you want to contribute to HiveMQ Mqtt Message Log Extension, see the link:CONTRIBUTING.md[contribution guidelines].

== License

HiveMQ Mqtt Message Log Extension is licensed under the `APACHE LICENSE, VERSION 2.0`. A copy of the license can be found link:LICENSE.txt[here].
